<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Palig.ICSS.data\Palig.ICSS.data.csproj" />
    <ProjectReference Include="..\Palig.ICSS.support\Palig.ICSS.support.csproj" />
  </ItemGroup>

</Project>
